version: "3"
services:
  kms:
    image: kurento/kurento-media-server:7.0.0
    container_name: kms
    platform: linux/amd64
    command: ["--gst-debug-level=3"]
    ports:
      - "8888:8888"
      - "5000-5050:5000-5050"
    environment:
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
